Web/DataGate.Web/Areas/Admin/Controllers/FundStorageController.cs
namespace DataGate.Web.Controllers.Funds
{
    using System.Threading.Tasks;

    using DataGate.Common;
    using DataGate.Services.Data.Storage.Contracts;
    using DataGate.Web.Infrastructure.Extensions;
    using DataGate.Web.InputModels.Funds;
    using DataGate.Web.Resources;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Area(EndpointsConstants.AdminAreaName)]
    [Authorize(Roles = GlobalConstants.AdministratorRoleName + "," + GlobalConstants.LegalRoleName)]
    public class FundStorageController : BaseController
    {
        private readonly IFundStorageService service;
        private readonly IFundSelectListService serviceSelect;
        private readonly SharedLocalizationService sharedLocalizer;

        public FundStorageController(
                        IFundStorageService fundService,
                        IFundSelectListService fundServiceSelect,
                        SharedLocalizationService sharedLocalizer)
        {
            this.service = fundService;
            this.serviceSelect = fundServiceSelect;
            this.sharedLocalizer = sharedLocalizer;
        }

        [Route("f/new")]
        public IActionResult Create()
        {
            this.SetViewDataValues();
            return this.View(new CreateFundInputModel());
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [Route("f/new")]
        public async Task<IActionResult> Create(
                     [Bind("InitialDate", "EndDate", "FundName", "CSSFCode", "Status",
                          "LegalForm", "LegalVehicle", "LegalType", "FACode", "DEPCode",
                          "TACode", "CompanyTypeDesc", "TinNumber", "LEICode", "RegNumber", "RecaptchaValue")] CreateFundInputModel model)
        {
            bool doesExist = await this.service.DoesExist(model.FundName);

            if (!this.ModelState.IsValid || doesExist)
            {
                if (doesExist)
                {
                    this.ShowError(this.sharedLocalizer.GetHtmlString(ErrorMessages.ExistingEntityName));
                }

                this.SetViewDataValues();
                return this.View(model);
            }

            var fundId = await this.service.Create(model);
            var date = DateTimeParser.ToWebFormat(model.InitialDate.AddDays(1));

            return this.ShowInfo(
                this.sharedLocalizer.GetHtmlString(InfoMessages.SuccessfulCreate),
                EndpointsConstants.RouteDetails + EndpointsConstants.FundArea,
                new { area = EndpointsConstants.FundArea, id = fundId, date = date });
        }

        [Route("f/edit/{id}/{date}")]
        public IActionResult Edit(int id, string date)
        {
            var model = this.service.GetByIdAndDate<EditFundInputModel>(id, date);
            model.InitialDate = model.InitialDate.AddDays(1);

            this.SetViewDataValues();

            return this.View(model);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [Route("f/edit/{id}/{date}")]
        public async Task<IActionResult> Edit(
                     [Bind("Id", "InitialDate", "FundName", "CSSFCode", "Status",
                          "LegalForm", "LegalVehicle", "LegalType", "FACode",
                          "DEPCode", "TACode", "CompanyTypeDesc", "TinNumber",
                          "LEICode", "RegNumber", "CommentTitle", "CommentArea", "RecaptchaValue")] EditFundInputModel model)
        {
            bool doesExistAtDate = await this.service.DoesExistAtDate(model.FundName, model.InitialDate);

            if (!this.ModelState.IsValid || doesExistAtDate)
            {
                if (doesExistAtDate)
                {
                    this.ShowError(this.sharedLocalizer.GetHtmlString(ErrorMessages.ExistingEntityAtDate));
                }

                this.SetViewDataValues();
                return this.View(model);
            }

            var fundId = await this.service.Edit(model);
            var date = DateTimeParser.ToWebFormat(model.InitialDate.AddDays(1));

            return this.ShowInfo(
                this.sharedLocalizer.GetHtmlString(InfoMessages.SuccessfulEdit),
                EndpointsConstants.RouteDetails + EndpointsConstants.FundArea,
                new { area = EndpointsConstants.FundArea, id = fundId, date = date });
        }

        private void SetViewDataValues()
        {
            this.ViewData["Status"] = this.serviceSelect.GetAllTbDomFStatus();
            this.ViewData["LegalForm"] = this.serviceSelect.GetAllTbDomLegalForm();
            this.ViewData["LegalVehicle"] = this.serviceSelect.GetAllTbDomLegalVehicle();
            this.ViewData["LegalType"] = this.serviceSelect.GetAllTbDomLegalType();
            this.ViewData["CompanyTypeDesc"] = this.serviceSelect.GetAllTbDomCompanyDesc();
        }
    }
}

Web/DataGate.Web/Areas/Admin/Views/FundStorage/Create.cshtml
@model CreateFundInputModel

@{
    ViewData["Title"] = SharedLocalizer.GetHtmlString("New Fund");
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="push">
    <div class="d-flex justify-content-center text-center">
        <form asp-controller="FundStorage"
              asp-action="Create"
              method="post"
              class="d-inline w-75">
            <h4 class="mb-5">@SharedLocalizer.GetHtmlString("Create New Fund")</h4>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="d-inline" id="div-inputs-to-format">

                <div class="column-form">
                    <div class="form-group">
                        <label asp-for="InitialDate"></label><br>
                        <input asp-for="InitialDate"
                               type="date"
                               min="2018-01-01"
                               class="form-control">
                        <span asp-validation-for="InitialDate" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="EndDate"></label><br>
                        <input asp-for="EndDate"
                               type="date"
                               class="form-control ">
                        <span asp-validation-for="EndDate" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="FundName"></label><br>
                        <input type="text"
                               class="form-control "
                               asp-for="FundName">
                        <span asp-validation-for="FundName" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="CSSFCode"></label><br>
                        <input type="text"
                               class="form-control "
                               asp-for="CSSFCode">
                        <span asp-validation-for="CSSFCode" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="LEICode"></label><br>
                        <input type="text"
                               class="form-control"
                               asp-for="LEICode">
                        <span asp-validation-for="LEICode" class="text-danger"></span>
                    </div>
                </div>

                <div class="column-form">
                    <div class="form-group">
                        <label asp-for="TinNumber"></label><br>
                        <input type="text"
                               class="form-control"
                               asp-for="TinNumber">
                        <span asp-validation-for="TinNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FACode"></label><br>
                        <input type="text"
                               class="form-control "
                               asp-for="FACode">
                        <span asp-validation-for="FACode" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="DEPCode"></label><br>
                        <input type="text"
                               class="form-control "
                               asp-for="DEPCode">
                        <span asp-validation-for="DEPCode" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="TACode"></label><br>
                        <input type="text"
                               class="form-control "
                               asp-for="TACode">
                        <span asp-validation-for="TACode" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="RegNumber"></label><br>
                        <input type="text"
                               class="form-control"
                               asp-for="RegNumber">
                        <span asp-validation-for="RegNumber" class="text-danger"></span>
                    </div>
                </div>

                <div class="column-form">
                    <div class="form-group">
                        <label asp-for="Status"></label><br>
                        <select class="select-pharus" asp-for="Status">
                            <option selected disabled value="0">-- Choose Status --</option>
                            @foreach (var status in (List<string>)ViewData["Status"])
                            {
                                <option value="@status">@status</option>
                            }
                        </select>
                    </div>
                    <span asp-validation-for="Status" class="text-danger"></span>
                    <div class="form-group">
                        <label asp-for="LegalForm"></label><br>
                        <select class="select-pharus" asp-for="LegalForm">
                            <option selected disabled value="0">-- Choose Form --</option>
                            @foreach (var form in (List<string>)ViewData["LegalForm"])
                            {
                                <option value="@form">@form</option>
                            }
                        </select>
                    </div>
                    <span asp-validation-for="LegalForm" class="text-danger"></span>

                    <div class="form-group">
                        <label asp-for="LegalVehicle"></label><br>
                        <select class="select-pharus" asp-for="LegalVehicle">
                            <option selected disabled>-- Choose Vehicle --</option>
                            @foreach (var vehicle in (List<string>)ViewData["LegalVehicle"])
                            {
                                <option value="@vehicle">@vehicle</option>
                            }
                        </select>
                    </div>
                    <span asp-validation-for="LegalVehicle" class="text-danger"></span>
                    <div class="form-group">
                        <label asp-for="LegalType"></label><br>
                        <select class="select-pharus" asp-for="LegalType">
                            <option selected disabled value="0">-- Choose Type --</option>
                            @foreach (var type in (List<string>)ViewData["LegalType"])
                            {
                                <option value="@type">@type</option>
                            }
                        </select>
                    </div>
                    <span asp-validation-for="LegalType" class="text-danger"></span>
                    <div class="form-group">
                        <label asp-for="CompanyTypeDesc"></label><br>
                        <select class="select-pharus" asp-for="CompanyTypeDesc">
                            <option selected disabled value="0">-- Choose Description --</option>
                            @foreach (var desc in (List<string>)ViewData["CompanyTypeDesc"])
                            {
                                <option value="@desc">@desc</option>
                            }
                        </select>
                    </div>
                    <span asp-validation-for="CompanyTypeDesc" class="text-danger"></span>
                </div>
            </div>

            <div class="button-holder my-4">
                <input type="hidden" id="RecaptchaValue" asp-for="RecaptchaValue" />
                <a class="btn btn-pharus btn-lg" asp-area="@EndpointsConstants.FundArea" asp-route="@EndpointsConstants.RouteAll@EndpointsConstants.FundsController">
                    @SharedLocalizer.GetHtmlString("Back to List")
                </a>
                <button type="submit"
                        class="btn btn-pharus btn-lg btn-confirm-create ml-5">
                    @SharedLocalizer.GetHtmlString("Create Fund")
                </button>
            </div>

        </form>
    </div>
</div>
@section Scripts{
    <partial name="Scripts/_CreateEditScriptsPartial">
}

Web/DataGate.Web/Areas/Admin/Views/FundStorage/Edit.cshtml
@model EditFundInputModel

@{
    ViewData["Title"] = SharedLocalizer.GetHtmlString("Edit Fund");
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="push">
    <div class="d-flex justify-content-center text-center">
        <form asp-controller="FundStorage"
              asp-action="Edit"
              method="post"
              class="d-inline w-75">
            <h4 class="mb-5">@SharedLocalizer.GetHtmlString("Edit Fund") @Model.FundName</h4>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="d-inline" id="div-inputs-to-format">
                <div class="form-group" hidden>
                    <label asp-for="Id" ></label><br>
                    <input type="text"
                           class="form-control "
                           asp-for="Id"
                           readonly>
                    <span asp-validation-for="Id" class="text-danger"></span>
                </div>

                <div class="column-form">
                    <div class="form-group">
                        <label asp-for="InitialDate" ></label><br>
                        <input asp-for="InitialDate"
                               type="date"
                               class="form-control ">
                        <span asp-validation-for="InitialDate" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="FundName" ></label><br>
                        <input type="text"
                               class="form-control "
                               asp-for="FundName">
                        <span asp-validation-for="FundName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CSSFCode" ></label><br>
                        <input type="text"
                               class="form-control "
                               asp-for="CSSFCode">
                        <span asp-validation-for="CSSFCode" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="LEICode" ></label><br>
                        <input type="text"
                               class="form-control "
                               asp-for="LEICode">
                        <span asp-validation-for="LEICode" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="TinNumber" ></label><br>
                        <input type="text"
                               class="form-control "
                               asp-for="TinNumber">
                        <span asp-validation-for="TinNumber" class="text-danger"></span>
                    </div>
                </div>

                <div class="column-form">
                    <div class="form-group">
                        <label asp-for="FACode" ></label><br>
                        <input type="text"
                               class="form-control "
                               asp-for="FACode">
                        <span asp-validation-for="FACode" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="DEPCode" ></label><br>
                        <input type="text"
                               class="form-control "
                               asp-for="DEPCode">
                        <span asp-validation-for="DEPCode" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="TACode" ></label><br>
                        <input type="text"
                               class="form-control "
                               asp-for="TACode">
                        <span asp-validation-for="TACode" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="RegNumber" ></label><br>
                        <input type="text"
                               class="form-control "
                               asp-for="RegNumber">
                        <span asp-validation-for="RegNumber" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="CommentTitle" ></label><br>
                        <input type="text"
                               class="form-control "
                               asp-for="CommentTitle">
                        <span asp-validation-for="CommentTitle" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="CommentArea" ></label><br>
                        <textarea class="form-control "
                                  asp-for="CommentArea">
                </textarea>
                        <span asp-validation-for="CommentArea" class="text-danger"></span>
                    </div>

                </div>

                <div class="column-form">
                    <div class="form-group">
                        <label asp-for="Status" ></label><br>
                        <select class="select-pharus" asp-for="Status">
                            @foreach (var status in (List<string>)ViewData["Status"])
                            {
                                if (status == Model.Status)
                                {
                                    <option selected value="@status">@status</option>
                                }
                                else
                                {
                                    <option value="@status">@status</option>
                                }
                            }
                        </select>
                    </div>
                    <span asp-validation-for="Status" class="text-danger"></span>
                    <div class="form-group">
                        <label asp-for="LegalForm" ></label><br>
                        <select class="select-pharus" asp-for="LegalForm">
                            @foreach (var form in (List<string>)ViewData["LegalForm"])
                            {
                                if (form == Model.LegalForm)
                                {
                                    <option selected value="@form">@form</option>
                                }
                                else
                                {
                                    <option value="@form">@form</option>
                                }
                            }
                        </select>
                    </div>
                    <span asp-validation-for="LegalForm" class="text-danger"></span>
                    <div class="form-group">
                        <label asp-for="LegalVehicle" ></label><br>
                        <select class="select-pharus" asp-for="LegalVehicle">
                            @foreach (var vehicle in (List<string>)ViewData["LegalVehicle"])
                            {
                                if (vehicle == Model.LegalVehicle)
                                {
                                    <option selected value="@vehicle">@vehicle</option>
                                }
                                else
                                {
                                    <option value="@vehicle">@vehicle</option>
                                }
                            }
                        </select>
                    </div>
                    <span asp-validation-for="LegalVehicle" class="text-danger"></span>

                    <div class="form-group">
                        <label asp-for="LegalType" ></label><br>
                        <select class="select-pharus" asp-for="LegalType">
                            @foreach (var type in (List<string>)ViewData["LegalType"])
                            {
                                if (type == Model.LegalType)
                                {
                                    <option selected value="@type">@type</option>
                                }
                                else
                                {
                                    <option value="@type">@type</option>
                                }
                            }
                        </select>
                    </div>
                    <span asp-validation-for="LegalType" class="text-danger"></span>
                    <div class="form-group">
                        <label asp-for="CompanyTypeDesc" ></label><br>
                        <select class="select-pharus" asp-for="CompanyTypeDesc">
                            @foreach (var desc in (List<string>)ViewData["CompanyTypeDesc"])
                            {
                                if (desc == Model.CompanyTypeDesc)
                                {
                                    <option selected value="@desc">@desc</option>
                                }
                                else
                                {
                                    <option value="@desc">@desc</option>
                                }
                            }
                        </select>
                    </div>
                    <span asp-validation-for="CompanyTypeDesc" class="text-danger"></span>
                </div>
            </div>

            <div class="button-holder my-4">
                <input type="hidden" id="RecaptchaValue" asp-for="RecaptchaValue" />
                <a class="btn btn-pharus btn-lg" asp-area="@EndpointsConstants.FundArea" asp-route="@EndpointsConstants.RouteAll@EndpointsConstants.FundsController">
                    @SharedLocalizer.GetHtmlString("Back to List")
                </a>
                <button type="submit"
                        class="btn btn-pharus btn-lg btn-confirm-update ml-5"
                        name="update_button">
                    @SharedLocalizer.GetHtmlString("Update Fund")
                </button>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    <partial name="Scripts/_CreateEditScriptsPartial">
}